spring:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&&useSSL=false
      username: root
      password: 123456
    secondary:
      url: jdbc:mysql://localhost:3306/test1?autoReconnect=true&useUnicode=true&&useSSL=false
      username: root
      password: 123456
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy