spring:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&&useSSL=false
      username: root
      password: 123456
    secondary:
      url: jdbc:mysql://localhost:3306/test1?autoReconnect=true&useUnicode=true&&useSSL=false
      username: root
      password: 123456
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  cache:
    type: redis
  redis:
    host: localhost
    password:
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8